---
- name: Carrega variáveis da família do sistema operacional
  ansible.builtin.include_vars:
    file: "{{ role_path }}/vars/{{ ansible_os_family | lower }}.yml"
  tags: devtools

- name: Instala os pacotes de desenvolvimento
  ansible.builtin.package:
    name: "{{ devtools_packages | map('extract', devtools_packages_map) | flatten | list }}"
  tags: devtools
