---
devtools_packages_map:
  build_tools:
    - build-essential
    - cmake
    - ninja-build
  c_compiler:
    - gcc
    - clang
  cpp_compiler:
    - g++
  go_lang:
    - golang-go
  java_sdk:
    - default-jdk
  python_tools:
    - python3-pip
    - virtualenv
  r_lang:
    - r-base
  rust_lang:
    - rustc
