---
- name: Gerencia o LibreOffice [{{  libreoffice_state }}]
  chocolatey.chocolatey.win_chocolatey:
    name: libreoffice
    state: "{{ libreoffice_state | default('present') }}"
  tags: libreoffice
