---
- name: Habilita Área de Trabalho Remota no Windows
  ansible.windows.win_powershell:
    script: |
      Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -value 0
      Enable-NetFirewallRule -DisplayGroup "Área de Trabalho Remota"
  when: ansible_system | lower == 'win32nt'
  tags: remotedesktop

- name: Instala o servidor X2Go
  ansible.builtin.package:
    name: x2goserver
  when: ansible_system | lower == 'linux'
  tags: remotedesktop
