---
- name: Inclui tarefas para o sistema {{ ansible_system }}
  include_tasks:
    file: "{{ item }}"
  with_first_found:
    - files:
      - "{{ ansible_system | lower }}.yml"
      skip: true
  tags: remotedesktop
